### ISSUE TITLE
Doesn't build with rust 1.93

### ISSUE THREAD

**Issue by jaques-sam** [Ghabriel/PokemonRust#7]
Build error:

```sh
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /home/sam/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/err-derive-0.1.6/src/lib.rs:145:63
    |
145 | fn display_body(s: &synstructure::Structure) -> Option<quote::__rt::TokenStream> {
    |                                                               ^^^^ could not find `__rt` in `quote`

For more information about this error, try `rustc --explain E0433`.
```

**Comment by jaques-sam** [comment]
Created an issue on err-derive: https://gitlab.com/torkleyy/err-derive/-/issues/19
